sudo: required

language: generic

services:
- docker

matrix:
  fast_finish: true
  include:
  - os: linux
    env: CHANNEL=stable
  - os: linux
    env: CHANNEL=stable
    if: type != pull_request
  - os: linux
    env: CHANNEL=nightly
    if: type != pull_request
  allow_failures:
  - env: CHANNEL=nightly

# Build the Bors staging and trying branches, plus PRs to master, and
# the latest release branch.
branches:
  only:
  - staging
  - trying
  - master
  - /release-.*/

# Install SDL development libraries from homebrew on macOS
before_install:
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update && brew install sdl2; fi"

# Generate documentation, compile the engine, run tests.
script:
- docker run -v `pwd`:/amethyst magnonellie/amethyst-docker-cache:$CHANNEL sh -exc 'ls / && mv ../amethyst-target target && sh travis.sh'
