sudo: required

language: rust

services:
- docker

matrix:
  fast_finish: true
  include:
  - os: linux
    rust: stable
#  - os: linux
#    rust: beta
#    if: type != pull_request
#  - os: linux
#    rust: nightly
#    if: type != pull_request
#  - os: windows
#    rust: stable
#    if: type != pull_request
#  - os: windows
#    rust: beta
#    if: type != pull_request
#  - os: windows
#    rust: nightly
#    if: type != pull_request
#  - os: osx
#    rust: stable
#    if: type != pull_request
#  - os: osx
#    rust: beta
#    if: type != pull_request
#  - os: osx
#    rust: nightly
#    if: type != pull_request
  allow_failures:
  - rust: nightly

branches:
  only:
  - staging
  - trying
  - master # remove

cache:
- cargo

before_script:
- export PATH=$PATH:/home/travis/.cargo/bin

# Generate documentation, compile the engine, run tests.
script:
- |
  docker run -v `pwd`:/amethyst magnonellie/amethyst-docker-cache:$CHANNEL \
  sh -exc 'sh travis.sh'
