sudo: required

language: generic

services:
- docker

matrix:
  fast_finish: true
  include:
  - os: linux
    env: CHANNEL=stable
  - os: linux
    env: CHANNEL=stable
    if: type != pull_request
  - os: linux
    env: CHANNEL=nightly
    if: type != pull_request
  - os: windows
    env: CHANNEL=stable
    if: type != pull_request
  - os: windows
    env: CHANNEL=beta
    if: type != pull_request
  - os: windows
    env: CHANNEL=nightly
    if: type != pull_request
  - os: osx
    env: CHANNEL=stable
    if: type != pull_request
  - os: osx
    env: CHANNEL=beta
    if: type != pull_request
  - os: osx
    env: CHANNEL=nightly
    if: type != pull_request
  allow_failures:
  - env: CHANNEL=nightly

branches:
  only:
  - staging
  - trying
  - master # remove

# Generate documentation, compile the engine, run tests.
script:
- |
  export RUSTFLAGS="-D warnings"

  echo "Build and test"
  cargo test --all --release

  if [ ${CHANNEL} = "stable" ]
  then
    if [ ${TRAVIS_OS_NAME} = "linux" ]
    then
      mdbook test book -L target/debug/deps
    fi

    echo "Build and test with sdl_controller"
    cargo check --all --release --features sdl_controller,profiler
  fi
