sudo: required

language: rust

addons:
  apt:
    packages:
    - libasound2-dev
    - libsdl2-dev

matrix:
  fast_finish: true
  include:
  - os: linux
    rust: stable
  - os: linux
    rust: beta
    if: type != pull_request
  - os: linux
    rust: nightly
    if: type != pull_request
#  - os: windows
#    rust: stable
#    if: type != pull_request
#  - os: windows
#    rust: beta
#    if: type != pull_request
#  - os: windows
#    rust: nightly
#    if: type != pull_request
#  - os: osx
#    rust: stable
#    if: type != pull_request
#  - os: osx
#    rust: beta
#    if: type != pull_request
#  - os: osx
#    rust: nightly
#    if: type != pull_request
  allow_failures:
  - rust: nightly

branches:
  only:
  - staging
  - trying
  - master # remove

before_install:
- |
  if [ ${TRAVIS_OS_NAME} = "windows" ]
  then
    wget --no-check-certificate https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
    7z x SDL2-devel-2.0.8-VC.zip
    cp SDL2-2.0.8\lib\x64\*.lib %USERPROFILE%\.rustup\toolchains\%TRAVIS_RUST_VERSION%-x86_64-pc-windows-msvc\lib\rustlib\%x86_64-pc-windows-msvc%\lib
    cp SDL2-2.0.8\lib\x64\*.dll .
    rm SDL2-devel-2.0.8-VC.zip
  elif [ ${TRAVIS_OS_NAME} = "osx" ]
  then
    brew update && brew install sdl2
  else
    curl -L -o mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/${MDBOOK_RELEASE}
    tar -xvf mdbook.tar.gz -C ./
    rm mdbook.tar.gz
  fi

before_script:
- export PATH=$PATH:/home/travis/.cargo/bin
- export RUSTFLAGS="-D warnings"

# Generate documentation, compile the engine, run tests.
script:
- |
  echo "Build and test"
  cargo test --all || exit 1

  if [ ${CHANNEL} = "stable" ]
  then
    if [ ${TRAVIS_OS_NAME} = "linux" ]
    then
      echo "Test book"
      mdbook test book -L target/debug/deps
    fi

    echo "Check common features"
    cargo check --all --features sdl_controller,profiler
  fi
