---
platform: linux

inputs:
- name: amethyst

run:
  path: sh
  dir: amethyst
  args:
  - -exc
  - |
    cargo --version
    export RUSTFLAGS="-D warnings"
    cargo check --all --features sdl_controller,profiler
    cargo test --all
