---
platform: linux

inputs:
- name: amethyst
- name: target

run:
  path: sh
  dir: amethyst
  args:
  - -exc
  - |
    rustc --version
    mdbook --version
    mdbook test book -L ../target/debug/deps
