version: 2
jobs:
  test-linux-stable:
    docker:
    - image: rustdocker/rust:stable
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          apt-get update && apt-get install -y \
          git libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev \
          python3 build-essential libsdl2-dev
    - run:
        name: Tests
        command: . ~/.cargo/env && cargo test --all
    - run:
        name: Fetch mdbook
        command: |
          curl -L -o mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/${MDBOOK_RELEASE}
          tar -xvf mdbook.tar.gz -C ./
          rm mdbook.tar.gz
    - run:
        name: Book
        command: mdbook test book -L target/debug/deps
    - run:
        name: Check features
        command: . ~/.cargo/env && cargo check --all --features sdl_controller,profiler
  test-linux-beta:
    docker:
    - image: rustdocker/rust:beta
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          apt-get update && apt-get install -y \
          git libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev \
          python3 build-essential libsdl2-dev
    - run:
        name: Tests
        command: . ~/.cargo/env && cargo test --all
  test-linux-nightly:
    docker:
    - image: rustdocker/rust:nightly
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          apt-get update && apt-get install -y \
          git libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev \
          python3 build-essential libsdl2-dev
    - run:
        name: Tests
        command: . ~/.cargo/env && cargo test --all

workflows:
  version: 2
  build_and_test:
    jobs:
    - test-linux-stable
    - test-linux-beta
    - test-linux-nightly
