version: 2
jobs:
  test-linux-stable:
    machine: true
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo apt-get update && sudo apt-get install -y \
          git libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev \
          python3 build-essential libsdl2-dev libsdl2-2.0-0 gcc libegl1-mesa-dev libgles2-mesa-dev && \
          wget "https://static.rust-lang.org/rustup/archive/%%RUSTUP-VERSION%%/${rustArch}/rustup-init" && \
          chmod +x rustup-init && \
          ./rustup-init -y --default-toolchain stable
    - run:
        name: Tests
        command: . ~/.cargo/env && cargo test --all
    - run:
        name: Fetch mdbook
        command: |
          curl -L -o mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/0.2.1
          tar -xvf mdbook.tar.gz -C ./
          rm mdbook.tar.gz
    - run:
        name: Book
        command: mdbook test book -L target/debug/deps
    - run:
        name: Check features
        command: . ~/.cargo/env && cargo check --all --features sdl_controller,profiler
  test-linux-beta:
    machine: true
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo apt-get update && sudo apt-get install -y \
          git libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev \
          python3 build-essential libsdl2-dev libsdl2-2.0-0 gcc libegl1-mesa-dev libgles2-mesa-dev && \
          wget "https://static.rust-lang.org/rustup/archive/%%RUSTUP-VERSION%%/${rustArch}/rustup-init" && \
          chmod +x rustup-init && \
          ./rustup-init -y --default-toolchain stable
    - run:
        name: Tests
        command: . ~/.cargo/env && cargo test --all
  test-linux-nightly:
    machine: true
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo apt-get update && sudo apt-get install -y \
          git libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev \
          python3 build-essential libsdl2-dev libsdl2-2.0-0 gcc libegl1-mesa-dev libgles2-mesa-dev && \
          wget "https://static.rust-lang.org/rustup/archive/%%RUSTUP-VERSION%%/${rustArch}/rustup-init" && \
          chmod +x rustup-init && \
          ./rustup-init -y --default-toolchain stable
    - run:
        name: Tests
        command: . ~/.cargo/env && cargo test --all

workflows:
  version: 2
  build_and_test:
    jobs:
    - test-linux-stable
    - test-linux-beta
    - test-linux-nightly
