---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rustdocker/rust
    tag: stable

inputs:
- name: amethyst

run:
  path: sh
  dir: amethyst
  args:
  - -exc
  - |
    apt-get update
    apt-get install -y libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev
    export PATH="$HOME/.cargo/bin:$PATH"
    cargo test --all -v
    cargo test --all --features profiler -v
    cargo test --all --features sdl_controller -v

