---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rustdocker/rust
    tag: stable

inputs:
- name: amethyst

outputs:
- name: target
  path: target

run:
  path: sh
  dir: amethyst
  args:
  - -exc
  - |
    echo "Fetching dependencies..."
    apt-get update > /dev/null
    apt-get install -y \
      libasound2-dev libx11-xcb-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb1-dev python3 \
      build-essential libsdl2-dev > /dev/null

    echo "Running tests..."
    export PATH="$HOME/.cargo/bin:$PATH"
    export RUSTFLAGS="-D warnings"
    cargo test --all --features profiler
    cargo test --all --features sdl_controller

    export CARGO_TARGET_DIR="../target"
    cargo test --all

caches:
- path: target
